version: '3'


services:
  nodejs_palomino:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs_palomino
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "11800:11898"	
    volumes:
      - .:/home/node/app_palomino
      - node_modules:/home/node/app_palomino/node_modules
    networks:
      - ap-network
    command: ./wait-for.sh db:27017 -- /home/node/app_palomino/node_modules/.bin/nodemon app.js


  db_palomino:
    image: mongo:4.1.8-xenial
    container_name: db_palomino
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:     
      - dbdata:/data/db_palomino
    networks:
      - ap-network  


networks:
  ap-network:
    driver: bridge


volumes:
  dbdata:
  node_modules:
